risk_per_trade: 0.01
max_lot: 5.0
min_lot: 0.01
kill_switch_dd: 0.20
soft_kill_dd: 0.15
max_holding_bars: 24
enable_forced_entry: true
enable_partial_tp: true
use_reentry: true
enable_spike_guard: true
meta_min_proba_thresh: 0.55
initial_capital: 100.0
commission_per_001_lot: 0.10
spread_points: 2.0
point_value: 0.1
ib_commission_per_lot: 7.0
n_walk_forward_splits: 5
output_base_dir: /content/drive/MyDrive/new
output_dir_name: gold_ai_run
data_file_path_m15: /content/drive/MyDrive/new/XAUUSD_M15.csv
data_file_path_m1: /content/drive/MyDrive/new/XAUUSD_M1.csv
config_file_path: /content/drive/MyDrive/new/config.yaml
meta_classifier_filename: meta_classifier.pkl
spike_model_filename: meta_classifier_spike.pkl
